// Code generated by gen-dart-client. DO NOT EDIT.
//
// IR source: dsl/domain/list-work-items.lisp
// IR sha256: bef58978256fe9f19af16f3d539041c168d2210c7a96c4a72e31eb43e3a32b0b
// IR kind:   query

/// GraphQL wire identifier for the list-work-items query.
/// Frontend code must reference this constant instead of hand-typing
/// the wire string (constraint C-006).
const String listWorkItemsQueryName = "workItems";

/// Result shape: list of work-item.
