// Code generated by gen-dart-client. DO NOT EDIT.
//
// IR source: dsl/domain/work-item.lisp
// IR sha256: 85dac41ffb84398e04b9de7c7237bd83afd8195883f2bf51342bbbee8d11b91f
// IR kind:   aggregate

class WorkItem {
  final String id;
  final String title;
  final String state;

  const WorkItem({
    required this.id,
    required this.title,
    required this.state,
  });

  factory WorkItem.fromJson(Map<String, dynamic> json) => WorkItem(
        id: json["id"] as String,
        title: json["title"] as String,
        state: json["state"] as String,
      );

  Map<String, dynamic> toJson() => {
        "id": id,
        "title": title,
        "state": state,
      };
}
