// Code generated by gen-dart-client. DO NOT EDIT.
//
// IR source: dsl/domain/work-item-created.lisp
// IR sha256: a96935c11b7d935788222a9a211ebfbed435b26f2bc13f68a2386291f45fb15a
// IR kind:   event

class WorkItemCreated {
  final String workItemId;
  final String title;

  const WorkItemCreated({
    required this.workItemId,
    required this.title,
  });

  factory WorkItemCreated.fromJson(Map<String, dynamic> json) => WorkItemCreated(
        workItemId: json["work_item_id"] as String,
        title: json["title"] as String,
      );

  Map<String, dynamic> toJson() => {
        "work_item_id": workItemId,
        "title": title,
      };
}

/// Wire identifier emitted in SSE payloads for [WorkItemCreated].
const String workItemCreatedEventName = "work-item-created";
